name: Ofertas del Profesor

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script del Profesor
        env:
          WEBHOOK_PROFESOR: ${{ secrets.WEBHOOK_PROFESOR }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python ofertas.py
