name: Ofertas del Profesor

on:
  schedule:
    # Se ejecuta a las 00:40 UTC (20:40 hora Chile UTC-4)
    - cron: '40 0 * * *'
  workflow_dispatch: # Permite seguir probando manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script del Profesor
        env:
          WEBHOOK_PROFESOR: ${{ secrets.WEBHOOK_PROFESOR }}
        run: python ofertas.py
